package com.dikin.fit1.ui.theme

import androidx.compose.ui.graphics.Color

// Light Mode
val primaryLight = Color(0xFF88511E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCC3)
val onPrimaryContainerLight = Color(0xFF2F1500)
val secondaryLight = Color(0xFF6F5D0E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFAE287)
val onSecondaryContainerLight = Color(0xFF221B00)
val tertiaryLight = Color(0xFF755B0B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDF95)
val onTertiaryContainerLight = Color(0xFF251A00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF221A14)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF221A14)
val surfaceVariantLight = Color(0xFFF3DFD2)
val onSurfaceVariantLight = Color(0xFF51443B)
val outlineLight = Color(0xFF847469)
val outlineVariantLight = Color(0xFFD6C3B6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382F28)
val inverseOnSurfaceLight = Color(0xFFFEEEE4)
val inversePrimaryLight = Color(0xFFFFB77D)
val surfaceDimLight = Color(0xFFE7D7CD)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E9)
val surfaceContainerLight = Color(0xFFFBEBE1)
val surfaceContainerHighLight = Color(0xFFF5E5DB)
val surfaceContainerHighestLight = Color(0xFFEFE0D6)

// Dark Mode
val primaryDark = Color(0xFFFFB77D)
val onPrimaryDark = Color(0xFF4D2600)
val primaryContainerDark = Color(0xFF6C3A06)
val onPrimaryContainerDark = Color(0xFFFFDCC3)
val secondaryDark = Color(0xFFDDC66E)
val onSecondaryDark = Color(0xFF3A3000)
val secondaryContainerDark = Color(0xFF544600)
val onSecondaryContainerDark = Color(0xFFFAE287)
val tertiaryDark = Color(0xFFE6C26C)
val onTertiaryDark = Color(0xFF3E2E00)
val tertiaryContainerDark = Color(0xFF594400)
val onTertiaryContainerDark = Color(0xFFFFDF95)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF19120C)
val onBackgroundDark = Color(0xFFEFE0D6)
val surfaceDark = Color(0xFF19120C)
val onSurfaceDark = Color(0xFFEFE0D6)
val surfaceVariantDark = Color(0xFF51443B)
val onSurfaceVariantDark = Color(0xFFD6C3B6)
val outlineDark = Color(0xFF9E8E82)
val outlineVariantDark = Color(0xFF51443B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFE0D6)
val inverseOnSurfaceDark = Color(0xFF382F28)
val inversePrimaryDark = Color(0xFF88511E)
val surfaceDimDark = Color(0xFF19120C)
val surfaceBrightDark = Color(0xFF413731)
val surfaceContainerLowestDark = Color(0xFF140D08)
val surfaceContainerLowDark = Color(0xFF221A14)
val surfaceContainerDark = Color(0xFF261E18)
val surfaceContainerHighDark = Color(0xFF312822)
val surfaceContainerHighestDark = Color(0xFF3C332C)
